### ISSUE TITLE
Feature Request & Porting to py3

### ISSUE THREAD

**Issue by anoduck** [jasonreisman/Timeline#9]
This is a very handy script to have around. Does a good job of simply generating json data to timeline svg images. 

Desperately needs to be officially ported to python3. At least two out of the five pull requests are available to accomplish this. 

If I can find the time, a few extra features could be added to make working with this script much easier. 

- dynamically determined sizes based on defined width.
- incorporation of argparse.
- etc, etc...

**Comment by mrchess** [comment]
I just found this library too and needed to use it with py3.

The adjustments I had to make was:

1. update tkinter imports https://github.com/jasonreisman/Timeline/blob/master/make_timeline.py#L10-L11
```
import tkinter.font as tkFont
import tkinter
```

2. remove `utf-8` encoding from last line https://github.com/jasonreisman/Timeline/blob/master/make_timeline.py#L255
```
print(timeline.to_string())
```

Then it ran for me!

**Comment by anoduck** [comment]
@mrchess I made similar changes as well, but for my purposes the print was much too tiny to use. So, a little more tinkering was needed to enlarge the print for use. Those modifications were extremely easy, which makes me wonder why the creator has not made them himself by now.
